### PR TITLE
Use string urls instead of URL objects

### PR DESCRIPTION
**Pull request by didair**
* Resolves issue with React Native not supporting `new URL`.
* Added missing dependency for running `jsdoc2md` command (added as dev dependency).

Resolves issue #35

### CODE REVIEW

**Comment by didair** [comment]
Accidentally used my global configuration for the first commit. But both are made by me.

**Comment by YourTechBud** [comment]
Can you change the the version in package.json to 0.8.1?

**Comment by didair** [comment]
Done

**Comment by didair** [comment]
I noticed 0.9.0 was release 2 hours ago. Should this be 0.9.1? @YourTechBud

**Comment by YourTechBud** [comment]
Yes lets keep the version v0.9.1. You also need to fix the merge conflicts.

**Comment by YourTechBud** [comment]
I made the necessary changes. Will make this live tomorrow! Thanks a ton @didair.

**Pull request merged**
